version: '3.8'
services:
  db-hoppscotch:
    image: postgres:15
    container_name: hoppscotch-postgres-db
    environment:
      POSTGRES_USER: ktq-hoppscotch
      POSTGRES_PASSWORD: kuditik1!
      POSTGRES_DB: hoppscotch
    ports:
      - 3003:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - hoppscotch-db_pgdata:/var/lib/postgresql/data
    networks:
      - hoppscotch-network

volumes:
  hoppscotch-db_pgdata:

networks:
  hoppscotch-network:
    driver: bridge